insert into chat.users (login, password) values('Roma', 123);
insert into chat.users (login, password) values('Dinar', 12345);
insert into chat.users (login, password) values('Nastya', 12386);
insert into chat.users (login, password) values('Masha', 12334);
insert into chat.users (login, password) values('Aidar', 12343);
insert into chat.rooms (name, owner) values('LobbyZXC', '1');
insert into chat.rooms (name, owner) values('Lobby2', '2');
insert into chat.rooms (name, owner) values('Lobby3', '3');
insert into chat.rooms (name, owner) values('Lobby4', '4');
insert into chat.rooms (name, owner) values('Lobby5', '5');
insert into chat.messages (author, chatroom, text, time) values('1', '1', 'go lobby 1x1!', 'Tue Apr 26 17:31:09 MSK 2022');
insert into chat.messages (author, chatroom, text, time) values('2', '2', 'go', 'Tue Apr 26 17:31:09 MSK 2022');
insert into chat.messages (author, chatroom, text, time) values('1', '3', 'go3', 'Tue Apr 26 17:31:09 MSK 2022');
insert into chat.messages (author, chatroom, text, time) values('4', '4', 'go4', 'Tue Apr 26 17:31:09 MSK 2022');
insert into chat.messages (author, chatroom, text, time) values('5', '5', 'go5', 'Tue Apr 26 17:31:09 MSK 2022');
